# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d20f24d680ab301288e6a3d8248f010cf80c042ac4d6c3cadc7b03b25c6a320d7a264c2cd681641bef50daa27cdc508b112ae14612724807c9e6187b38aa6405

test:
  secret_key_base: 36909155d2d26abdde4e2e313ea9695899f721f599d2a6efbbff3e03a07d14ab7e13b38e5579eea94f5960fccd25a53f7540a72acf587f28c5688af6e0ec74bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
